version: '3.4'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: skyline_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./database:/var/lib/mysql
  redis-server:
    restart: always
    image: redis:latest
    container_name: skyline_redis
    command: redis-server /etc/redis.conf
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis.conf
      - tmp:/tmp/
      - ./redis:/data
    networks:
      - mysqlnetwork
  skyline:
    build: 
      context: . #current dir as build context
      target: run_skyline
    image: skyline
    depends_on:
      - mysql
      - redis-server
    ports:
      - "443:443"
    volumes:
      - tmp:/tmp/
volumes:
  tmp:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
networks:
  mysqlnetwork:
    driver: bridge
  




