version: '3.4'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: skyline_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'  # If mysql container password changes here - change it in the environment below
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  redis-server:
    restart: always
    image: redis:latest
    container_name: skyline_redis
    command: redis-server /etc/redis.conf
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis.conf
      - tmp:/tmp/
      - ./redis:/data
  skyline:
    build: 
      context: . #current dir as build context
      target: run_skyline
    image: skyline
    depends_on:
      - mysql
      - redis-server
    ports:
      - 443:443
    volumes:
      - tmp:/tmp/
    environment:
        PANORAMA_DBHOST: skyline_mysql
        MYSQL_ROOT_PASSWORD: 'password' # If mysql container password changes above - change it here as well
volumes:
  tmp:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
  




