version: '3.4'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: skyline_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./database:/var/lib/mysql
  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    networks:
      - mysqlnetwork
  skyline:
    build: 
      context: . #current dir as build context
      target: run_skyline
    image: skyline:latest
    volumes:
      - .:/skyline
    depends_on:
      - mysql
      - redis-server
volumes:
  mysql:
    driver: local
  redis:
    driver: local
networks:
  mysqlnetwork:
    driver: bridge
  




